name: Automation CI/CD Pipeline

# Trigger / Kapan Action-nya jalan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  automation-api-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checkout the repository

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Test API
      - name: Install API dependencies
        working-directory: ./api
        run: npm install

      - name: Run API Tests
        working-directory: ./api
        run: npm test

      # Test Web UI
      - name: Install Web UI dependencies
        working-directory: ./web-ui
        run: npm install

      - name: Run Web UI Tests
        working-directory: ./web-ui
        run: npm test -- --coverage --watchAll=false

      - name: Build Web UI
        working-directory: ./web-ui
        run: npm run build

      # Create README for test reports
      - name: Create README for test reports
        run: |
          mkdir -p reports
          cat > reports/README.md << 'EOF'
          # Test Report Instructions

          This directory contains test reports for both the API and Web UI components of the project.

          ## How to Open Test Reports

          ### API Test Report
          1. Navigate to the `api-test-results` directory
          2. Locate the `html-report/test-report.html` file
          3. Open this file with any web browser (Chrome, Firefox, Edge, etc.)
          4. You can simply double-click the file or right-click and select "Open with" and choose your browser

          ### Web UI Test Report and Coverage
          1. Navigate to the `web-ui-test-results` directory 
          2. Open the `html-report/test-report.html` file in your browser for a summary
          3. For detailed coverage reports, open `coverage/lcov-report/index.html` in your browser
          4. The coverage report shows which parts of the code are covered by tests (green) and which are not (red)

          ## Notes
          - These reports provide a user-friendly way to view test results
          - Coverage reports are interactive - you can click on files to see detailed line-by-line coverage
          - Green lines in coverage reports indicate code that was executed during tests
          - Red lines indicate code that was not executed during tests

          ## Troubleshooting
          If you have trouble opening the HTML files:
          1. Make sure you've fully extracted the zip file
          2. Try using a different browser
          3. Check if you have permission to access the files
          EOF

      # Archive test results (API)
      - name: Archive API test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: api-test-results
          path: api

      # Archive test results (Web UI)
      - name: Archive Web UI test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: web-ui-test-results
          path: web-ui

      # Archive README
      - name: Archive README
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: instructions
          path: reports/README.md
